/*
 * @Description: 医生数据
 * @Author: zhang zhen
 * @Date: 2022-02-21 17:39:38
 * @LastEditors: zhang zhen
 * @LastEditTime: 2022-02-21 17:45:10
 * @FilePath: /servers/model/docker.js
 */
const newList = {
  result: {
    schDocResultList: [
      {
        deptName: "眼科",
        goodAt: "暂无介绍",
        docNamePinYin: "gyr",
        docId: "2078101",
        deptId: "1026",
        docTitle: "副主任医师",
        hosId: "570",
        docPhoto: "",
        docJob: "",
        docName: "葛轶睿",
        docSecondResultList: [
          { schDate: "02-24", schState: "2" },
          { schDate: "02-25", schState: "0" },
        ],
        showNo: "90000",
        docState: "0",
        docTitleName: "副主任医师",
        hosName: "东部战区总医院",
      },
      {
        deptName: "眼科",
        goodAt: "暂无介绍",
        docNamePinYin: "hzp",
        docId: "2078016",
        deptId: "1026",
        docTitle: "主任医师",
        hosId: "570",
        docPhoto: "",
        docJob: "",
        docName: "黄振平",
        docSecondResultList: [
          { schDate: "02-24", schState: "2" },
          { schDate: "02-28", schState: "2" },
        ],
        showNo: "90000",
        docState: "2",
        docTitleName: "主任医师",
        hosName: "东部战区总医院",
      },
      {
        deptName: "眼科",
        goodAt: "暂无介绍",
        docNamePinYin: "jt",
        docId: "2078081",
        deptId: "1026",
        docTitle: "副主任医师",
        hosId: "570",
        docPhoto: "",
        docJob: "",
        docName: "姜涛",
        docSecondResultList: [{ schDate: "02-22", schState: "0" }],
        showNo: "90000",
        docState: "0",
        docTitleName: "副主任医师",
        hosName: "东部战区总医院",
      },
      {
        deptName: "眼科",
        goodAt: "暂无介绍",
        docNamePinYin: "ly",
        docId: "2084018",
        deptId: "1026",
        docTitle: "副主任医师",
        hosId: "570",
        docPhoto: "",
        docJob: "",
        docName: "陆燕",
        docSecondResultList: [
          { schDate: "02-22", schState: "0" },
          { schDate: "02-25", schState: "0" },
        ],
        showNo: "90000",
        docState: "0",
        docTitleName: "副主任医师",
        hosName: "东部战区总医院",
      },
      {
        deptName: "眼科",
        goodAt: "暂无介绍",
        docNamePinYin: "wll",
        docId: "2077970",
        deptId: "1026",
        docTitle: "副主任医师",
        hosId: "570",
        docPhoto: "",
        docJob: "",
        docName: "王理理",
        docSecondResultList: [
          { schDate: "02-24", schState: "0" },
          { schDate: "02-28", schState: "0" },
        ],
        showNo: "90000",
        docState: "0",
        docTitleName: "副主任医师",
        hosName: "东部战区总医院",
      },
      {
        deptName: "眼科",
        goodAt: "暂无介绍",
        docNamePinYin: "wy",
        docId: "2083379",
        deptId: "1026",
        docTitle: "副主任医师",
        hosId: "570",
        docPhoto: "",
        docJob: "",
        docName: "吴艳",
        docSecondResultList: [
          { schDate: "02-21", schState: "0" },
          { schDate: "02-23", schState: "0" },
          { schDate: "02-26", schState: "0" },
          { schDate: "02-28", schState: "0" },
        ],
        showNo: "90000",
        docState: "0",
        docTitleName: "副主任医师",
        hosName: "东部战区总医院",
      },
      {
        deptName: "眼科",
        goodAt: "暂无介绍",
        docNamePinYin: "wy",
        docId: "2078104",
        deptId: "1026",
        docTitle: "副主任医师",
        hosId: "570",
        docPhoto: "",
        docJob: "",
        docName: "吴勇",
        docSecondResultList: [
          { schDate: "02-23", schState: "0" },
          { schDate: "02-25", schState: "0" },
        ],
        showNo: "90000",
        docState: "0",
        docTitleName: "副主任医师",
        hosName: "东部战区总医院",
      },
      {
        deptName: "眼科",
        goodAt: "暂无介绍",
        docNamePinYin: "xcy",
        docId: "2077953",
        deptId: "1026",
        docTitle: "主任医师",
        hosId: "570",
        docPhoto: "",
        docJob: "",
        docName: "薛春燕",
        docSecondResultList: [{ schDate: "02-23", schState: "2" }],
        showNo: "90000",
        docState: "2",
        docTitleName: "主任医师",
        hosName: "东部战区总医院",
      },
      {
        deptName: "眼科",
        goodAt: "暂无介绍",
        docNamePinYin: "yf",
        docId: "2078059",
        deptId: "1026",
        docTitle: "副主任医师",
        hosId: "570",
        docPhoto: "",
        docJob: "",
        docName: "闫峰",
        docSecondResultList: [
          { schDate: "02-21", schState: "0" },
          { schDate: "02-24", schState: "0" },
          { schDate: "02-28", schState: "0" },
        ],
        showNo: "90000",
        docState: "0",
        docTitleName: "副主任医师",
        hosName: "东部战区总医院",
      },
      {
        deptName: "眼科",
        goodAt: "暂无介绍",
        docNamePinYin: "yj",
        docId: "2078058",
        deptId: "1026",
        docTitle: "副主任医师",
        hosId: "570",
        docPhoto: "",
        docJob: "",
        docName: "尹婕",
        docSecondResultList: [
          { schDate: "02-22", schState: "0" },
          { schDate: "02-23", schState: "0" },
        ],
        showNo: "90000",
        docState: "0",
        docTitleName: "副主任医师",
        hosName: "东部战区总医院",
      },
      {
        deptName: "眼科",
        goodAt: "暂无介绍",
        docNamePinYin: "zzl",
        docId: "2078057",
        deptId: "1026",
        docTitle: "副主任医师",
        hosId: "570",
        docPhoto: "",
        docJob: "",
        docName: "赵长霖",
        docSecondResultList: [
          { schDate: "02-24", schState: "0" },
          { schDate: "02-28", schState: "0" },
        ],
        showNo: "90000",
        docState: "0",
        docTitleName: "副主任医师",
        hosName: "东部战区总医院",
      },
    ],
  },
  timeTaken: 10,
  code: "0",
  message: "成功",
  respCode: "999002",
};

module.exports = newList
